framework:
    messenger:
      transports:
        async:
          dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
          serializer: messenger.transport.symfony_serializer
          options:
            auto_setup: true
            exchange:
              name: messages
              type: direct
              default_publish_routing_key: from_external
            queues:
              messages:
                binding_keys: [ from_external ]

      routing:
        'App\Message\UserInfo': async
